// import { parseUnits } from 'ethers';
// import { getLatestRewardsClaimed } from '@/lib/getLatestRewardsClaimed';

// import { borrow } from '@/lib/borrow';
// import { repay } from '@/lib/repay';
// import { supplyWithPermit } from '@/lib/supply';
// import { supplyETH } from '@/lib/supplyETH';
// import { borrowETH } from '@/lib/borrowETH';
// import { withdrawETH } from '@/lib/withdrawETH';
// import { repayETH } from '@/lib/repayETH';
// import { getInterstRate } from '@/lib/interstRate';
// import { withdrawIPWithPermit } from '@/lib/withdrawIPWithPermit';
// import { borrowPermit } from '@/lib/borrowPermit';
// import { configIncentiveAssets } from '@/lib/configIncentiveAssets';
// import { claimReward } from '@/lib/claimReward';
// import { claimAllReward } from '@/lib/claimAllRewards';
// import { calculateDAIIncentiveAPR } from '@/lib/calculateAssetIncentiveAPR';
// import { liquidation } from '@/lib/liquidation';
// import { preLiquidation } from '@/lib/liquidation';
// import { faucet } from '@/lib/faucet';
// import { preFaucet } from '@/lib/faucet';
// import { WETH_ADDRESS, signer } from '@/utils/config';

// supplyWithPermit(DAI_ADDRESS, parseUnits('10', 18));
// borrow(DAI_ADDRESS, parseUnits('1', 18));
// repay();
// supplyETH();
// borrowETH();
// withdrawETH();
// repayETH();
// getInterstRate();
// withdrawIPWithPermit();
// borrowPermit();
// configIncentiveAssets();
// claimReward();
// claimAllReward();
// getLatestRewardsClaimed(signer.address);
// calculateDAIIncentiveAPR();
// preLiquidation();
// liquidation();
// preFaucet();
// faucet(WETH_ADDRESS, signer.address, parseUnits('100', 18));
