// import { parseUnits } from 'ethers';
// import { getLatestRewardsClaimed } from '@/lib/getLatestRewardsClaimed';
// import { ethers } from 'ethers';

// import { borrow } from '@/lib/borrow';
// import { repay } from '@/lib/repay';
// import { supplyWithPermit } from '@/lib/supply';
// import { DAI_ADDRESS } from '@/utils/config';
// import { supplyIP } from '@/lib/supplyIP';
// import { borrowIP } from '@/lib/borrowIP';
// import { withdrawIP } from '@/lib/withdrawIP';
// import { repayIP } from '@/lib/repayIP';
// import { getInterstRate } from '@/lib/interstRate';
// import { withdrawIPWithPermit } from '@/lib/withdrawIPWithPermit';
// import { borrowPermit } from '@/lib/borrowPermit';
// import { configInsentiveAssets } from '@/lib/configInsentiveAssets';
// import { claimReward } from '@/lib/claimReward';
// import { claimAllReward } from '@/lib/claimAllRewards';
// import { calculateDAIIncentiveAPR } from '@/lib/calculateAssetIncentiveAPR';
import { liquidation } from '@/lib/liquidation';

// supplyWithPermit(DAI_ADDRESS, ethers.parseUnits('10', 18));
// borrow(DAI_ADDRESS, parseUnits('1', 10));
// repay();
// supplyIP();
// borrowIP();
// withdrawIP();
// repayIP();
// getInterstRate();
// withdrawIPWithPermit();
// borrowPermit();
// configInsentiveAssets();
// claimReward();
// claimAllReward();
// getLatestRewardsClaimed(signer.address);
// calculateDAIIncentiveAPR();
// preLiquidation();
liquidation();
