/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AaveOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESSES_PROVIDER"
      | "BASE_CURRENCY"
      | "BASE_CURRENCY_UNIT"
      | "getAssetPrice"
      | "getAssetsPrices"
      | "getFallbackOracle"
      | "getPriceIdOfAsset"
      | "getPyth"
      | "pyth"
      | "setAssetsPriceIds"
      | "setFallbackOracle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetPriceIdUpdated"
      | "AssetSourceUpdated"
      | "BaseCurrencySet"
      | "FallbackOracleUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_CURRENCY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASE_CURRENCY_UNIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetsPrices",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFallbackOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceIdOfAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getPyth", values?: undefined): string;
  encodeFunctionData(functionFragment: "pyth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAssetsPriceIds",
    values: [AddressLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setFallbackOracle",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_CURRENCY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BASE_CURRENCY_UNIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetsPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFallbackOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceIdOfAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPyth", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pyth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAssetsPriceIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFallbackOracle",
    data: BytesLike
  ): Result;
}

export namespace AssetPriceIdUpdatedEvent {
  export type InputTuple = [asset: AddressLike, priceId: BytesLike];
  export type OutputTuple = [asset: string, priceId: string];
  export interface OutputObject {
    asset: string;
    priceId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetSourceUpdatedEvent {
  export type InputTuple = [asset: AddressLike, source: AddressLike];
  export type OutputTuple = [asset: string, source: string];
  export interface OutputObject {
    asset: string;
    source: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BaseCurrencySetEvent {
  export type InputTuple = [
    baseCurrency: AddressLike,
    baseCurrencyUnit: BigNumberish
  ];
  export type OutputTuple = [baseCurrency: string, baseCurrencyUnit: bigint];
  export interface OutputObject {
    baseCurrency: string;
    baseCurrencyUnit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FallbackOracleUpdatedEvent {
  export type InputTuple = [fallbackOracle: AddressLike];
  export type OutputTuple = [fallbackOracle: string];
  export interface OutputObject {
    fallbackOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AaveOracle extends BaseContract {
  connect(runner?: ContractRunner | null): AaveOracle;
  waitForDeployment(): Promise<this>;

  interface: AaveOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESSES_PROVIDER: TypedContractMethod<[], [string], "view">;

  BASE_CURRENCY: TypedContractMethod<[], [string], "view">;

  BASE_CURRENCY_UNIT: TypedContractMethod<[], [bigint], "view">;

  getAssetPrice: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  getAssetsPrices: TypedContractMethod<
    [assets: AddressLike[]],
    [bigint[]],
    "view"
  >;

  getFallbackOracle: TypedContractMethod<[], [string], "view">;

  getPriceIdOfAsset: TypedContractMethod<
    [asset: AddressLike],
    [string],
    "view"
  >;

  getPyth: TypedContractMethod<[], [string], "view">;

  pyth: TypedContractMethod<[], [string], "view">;

  setAssetsPriceIds: TypedContractMethod<
    [assets: AddressLike[], priceIds: BytesLike[]],
    [void],
    "nonpayable"
  >;

  setFallbackOracle: TypedContractMethod<
    [fallbackOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESSES_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BASE_CURRENCY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BASE_CURRENCY_UNIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssetPrice"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssetsPrices"
  ): TypedContractMethod<[assets: AddressLike[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getFallbackOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPriceIdOfAsset"
  ): TypedContractMethod<[asset: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPyth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pyth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAssetsPriceIds"
  ): TypedContractMethod<
    [assets: AddressLike[], priceIds: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFallbackOracle"
  ): TypedContractMethod<[fallbackOracle: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssetPriceIdUpdated"
  ): TypedContractEvent<
    AssetPriceIdUpdatedEvent.InputTuple,
    AssetPriceIdUpdatedEvent.OutputTuple,
    AssetPriceIdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AssetSourceUpdated"
  ): TypedContractEvent<
    AssetSourceUpdatedEvent.InputTuple,
    AssetSourceUpdatedEvent.OutputTuple,
    AssetSourceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BaseCurrencySet"
  ): TypedContractEvent<
    BaseCurrencySetEvent.InputTuple,
    BaseCurrencySetEvent.OutputTuple,
    BaseCurrencySetEvent.OutputObject
  >;
  getEvent(
    key: "FallbackOracleUpdated"
  ): TypedContractEvent<
    FallbackOracleUpdatedEvent.InputTuple,
    FallbackOracleUpdatedEvent.OutputTuple,
    FallbackOracleUpdatedEvent.OutputObject
  >;

  filters: {
    "AssetPriceIdUpdated(address,bytes32)": TypedContractEvent<
      AssetPriceIdUpdatedEvent.InputTuple,
      AssetPriceIdUpdatedEvent.OutputTuple,
      AssetPriceIdUpdatedEvent.OutputObject
    >;
    AssetPriceIdUpdated: TypedContractEvent<
      AssetPriceIdUpdatedEvent.InputTuple,
      AssetPriceIdUpdatedEvent.OutputTuple,
      AssetPriceIdUpdatedEvent.OutputObject
    >;

    "AssetSourceUpdated(address,address)": TypedContractEvent<
      AssetSourceUpdatedEvent.InputTuple,
      AssetSourceUpdatedEvent.OutputTuple,
      AssetSourceUpdatedEvent.OutputObject
    >;
    AssetSourceUpdated: TypedContractEvent<
      AssetSourceUpdatedEvent.InputTuple,
      AssetSourceUpdatedEvent.OutputTuple,
      AssetSourceUpdatedEvent.OutputObject
    >;

    "BaseCurrencySet(address,uint256)": TypedContractEvent<
      BaseCurrencySetEvent.InputTuple,
      BaseCurrencySetEvent.OutputTuple,
      BaseCurrencySetEvent.OutputObject
    >;
    BaseCurrencySet: TypedContractEvent<
      BaseCurrencySetEvent.InputTuple,
      BaseCurrencySetEvent.OutputTuple,
      BaseCurrencySetEvent.OutputObject
    >;

    "FallbackOracleUpdated(address)": TypedContractEvent<
      FallbackOracleUpdatedEvent.InputTuple,
      FallbackOracleUpdatedEvent.OutputTuple,
      FallbackOracleUpdatedEvent.OutputObject
    >;
    FallbackOracleUpdated: TypedContractEvent<
      FallbackOracleUpdatedEvent.InputTuple,
      FallbackOracleUpdatedEvent.OutputTuple,
      FallbackOracleUpdatedEvent.OutputObject
    >;
  };
}
