/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IUiPoolDataProviderV3 {
  export type AggregatedReserveDataStruct = {
    underlyingAsset: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
    baseLTVasCollateral: BigNumberish;
    reserveLiquidationThreshold: BigNumberish;
    reserveLiquidationBonus: BigNumberish;
    reserveFactor: BigNumberish;
    usageAsCollateralEnabled: boolean;
    borrowingEnabled: boolean;
    stableBorrowRateEnabled: boolean;
    isActive: boolean;
    isFrozen: boolean;
    liquidityIndex: BigNumberish;
    variableBorrowIndex: BigNumberish;
    liquidityRate: BigNumberish;
    variableBorrowRate: BigNumberish;
    stableBorrowRate: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    aTokenAddress: AddressLike;
    stableDebtTokenAddress: AddressLike;
    variableDebtTokenAddress: AddressLike;
    interestRateStrategyAddress: AddressLike;
    availableLiquidity: BigNumberish;
    totalPrincipalStableDebt: BigNumberish;
    averageStableRate: BigNumberish;
    stableDebtLastUpdateTimestamp: BigNumberish;
    totalScaledVariableDebt: BigNumberish;
    priceInMarketReferenceCurrency: BigNumberish;
    priceOracle: AddressLike;
    variableRateSlope1: BigNumberish;
    variableRateSlope2: BigNumberish;
    stableRateSlope1: BigNumberish;
    stableRateSlope2: BigNumberish;
    baseStableBorrowRate: BigNumberish;
    baseVariableBorrowRate: BigNumberish;
    optimalUsageRatio: BigNumberish;
    isPaused: boolean;
    isSiloedBorrowing: boolean;
    accruedToTreasury: BigNumberish;
    unbacked: BigNumberish;
    isolationModeTotalDebt: BigNumberish;
    flashLoanEnabled: boolean;
    debtCeiling: BigNumberish;
    debtCeilingDecimals: BigNumberish;
    eModeCategoryId: BigNumberish;
    borrowCap: BigNumberish;
    supplyCap: BigNumberish;
    eModeLtv: BigNumberish;
    eModeLiquidationThreshold: BigNumberish;
    eModeLiquidationBonus: BigNumberish;
    eModePriceSource: AddressLike;
    eModeLabel: string;
    borrowableInIsolation: boolean;
  };

  export type AggregatedReserveDataStructOutput = [
    underlyingAsset: string,
    name: string,
    symbol: string,
    decimals: bigint,
    baseLTVasCollateral: bigint,
    reserveLiquidationThreshold: bigint,
    reserveLiquidationBonus: bigint,
    reserveFactor: bigint,
    usageAsCollateralEnabled: boolean,
    borrowingEnabled: boolean,
    stableBorrowRateEnabled: boolean,
    isActive: boolean,
    isFrozen: boolean,
    liquidityIndex: bigint,
    variableBorrowIndex: bigint,
    liquidityRate: bigint,
    variableBorrowRate: bigint,
    stableBorrowRate: bigint,
    lastUpdateTimestamp: bigint,
    aTokenAddress: string,
    stableDebtTokenAddress: string,
    variableDebtTokenAddress: string,
    interestRateStrategyAddress: string,
    availableLiquidity: bigint,
    totalPrincipalStableDebt: bigint,
    averageStableRate: bigint,
    stableDebtLastUpdateTimestamp: bigint,
    totalScaledVariableDebt: bigint,
    priceInMarketReferenceCurrency: bigint,
    priceOracle: string,
    variableRateSlope1: bigint,
    variableRateSlope2: bigint,
    stableRateSlope1: bigint,
    stableRateSlope2: bigint,
    baseStableBorrowRate: bigint,
    baseVariableBorrowRate: bigint,
    optimalUsageRatio: bigint,
    isPaused: boolean,
    isSiloedBorrowing: boolean,
    accruedToTreasury: bigint,
    unbacked: bigint,
    isolationModeTotalDebt: bigint,
    flashLoanEnabled: boolean,
    debtCeiling: bigint,
    debtCeilingDecimals: bigint,
    eModeCategoryId: bigint,
    borrowCap: bigint,
    supplyCap: bigint,
    eModeLtv: bigint,
    eModeLiquidationThreshold: bigint,
    eModeLiquidationBonus: bigint,
    eModePriceSource: string,
    eModeLabel: string,
    borrowableInIsolation: boolean
  ] & {
    underlyingAsset: string;
    name: string;
    symbol: string;
    decimals: bigint;
    baseLTVasCollateral: bigint;
    reserveLiquidationThreshold: bigint;
    reserveLiquidationBonus: bigint;
    reserveFactor: bigint;
    usageAsCollateralEnabled: boolean;
    borrowingEnabled: boolean;
    stableBorrowRateEnabled: boolean;
    isActive: boolean;
    isFrozen: boolean;
    liquidityIndex: bigint;
    variableBorrowIndex: bigint;
    liquidityRate: bigint;
    variableBorrowRate: bigint;
    stableBorrowRate: bigint;
    lastUpdateTimestamp: bigint;
    aTokenAddress: string;
    stableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    availableLiquidity: bigint;
    totalPrincipalStableDebt: bigint;
    averageStableRate: bigint;
    stableDebtLastUpdateTimestamp: bigint;
    totalScaledVariableDebt: bigint;
    priceInMarketReferenceCurrency: bigint;
    priceOracle: string;
    variableRateSlope1: bigint;
    variableRateSlope2: bigint;
    stableRateSlope1: bigint;
    stableRateSlope2: bigint;
    baseStableBorrowRate: bigint;
    baseVariableBorrowRate: bigint;
    optimalUsageRatio: bigint;
    isPaused: boolean;
    isSiloedBorrowing: boolean;
    accruedToTreasury: bigint;
    unbacked: bigint;
    isolationModeTotalDebt: bigint;
    flashLoanEnabled: boolean;
    debtCeiling: bigint;
    debtCeilingDecimals: bigint;
    eModeCategoryId: bigint;
    borrowCap: bigint;
    supplyCap: bigint;
    eModeLtv: bigint;
    eModeLiquidationThreshold: bigint;
    eModeLiquidationBonus: bigint;
    eModePriceSource: string;
    eModeLabel: string;
    borrowableInIsolation: boolean;
  };

  export type BaseCurrencyInfoStruct = {
    marketReferenceCurrencyUnit: BigNumberish;
    marketReferenceCurrencyPriceInUsd: BigNumberish;
    networkBaseTokenPriceInUsd: BigNumberish;
    networkBaseTokenPriceDecimals: BigNumberish;
  };

  export type BaseCurrencyInfoStructOutput = [
    marketReferenceCurrencyUnit: bigint,
    marketReferenceCurrencyPriceInUsd: bigint,
    networkBaseTokenPriceInUsd: bigint,
    networkBaseTokenPriceDecimals: bigint
  ] & {
    marketReferenceCurrencyUnit: bigint;
    marketReferenceCurrencyPriceInUsd: bigint;
    networkBaseTokenPriceInUsd: bigint;
    networkBaseTokenPriceDecimals: bigint;
  };

  export type UserReserveDataStruct = {
    underlyingAsset: AddressLike;
    scaledATokenBalance: BigNumberish;
    usageAsCollateralEnabledOnUser: boolean;
    stableBorrowRate: BigNumberish;
    scaledVariableDebt: BigNumberish;
    principalStableDebt: BigNumberish;
    stableBorrowLastUpdateTimestamp: BigNumberish;
  };

  export type UserReserveDataStructOutput = [
    underlyingAsset: string,
    scaledATokenBalance: bigint,
    usageAsCollateralEnabledOnUser: boolean,
    stableBorrowRate: bigint,
    scaledVariableDebt: bigint,
    principalStableDebt: bigint,
    stableBorrowLastUpdateTimestamp: bigint
  ] & {
    underlyingAsset: string;
    scaledATokenBalance: bigint;
    usageAsCollateralEnabledOnUser: boolean;
    stableBorrowRate: bigint;
    scaledVariableDebt: bigint;
    principalStableDebt: bigint;
    stableBorrowLastUpdateTimestamp: bigint;
  };
}

export interface UiPoolDataProviderV3Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "ETH_CURRENCY_UNIT"
      | "MKR_ADDRESS"
      | "bytes32ToString"
      | "getReservesData"
      | "getReservesList"
      | "getUserReservesData"
      | "marketReferenceCurrencyPriceInUsdPriceId"
      | "networkBaseTokenPriceInUsdPriceId"
      | "pyth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ETH_CURRENCY_UNIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MKR_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserReservesData",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketReferenceCurrencyPriceInUsdPriceId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "networkBaseTokenPriceInUsdPriceId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pyth", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ETH_CURRENCY_UNIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MKR_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserReservesData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketReferenceCurrencyPriceInUsdPriceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkBaseTokenPriceInUsdPriceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pyth", data: BytesLike): Result;
}

export interface UiPoolDataProviderV3 extends BaseContract {
  connect(runner?: ContractRunner | null): UiPoolDataProviderV3;
  waitForDeployment(): Promise<this>;

  interface: UiPoolDataProviderV3Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ETH_CURRENCY_UNIT: TypedContractMethod<[], [bigint], "view">;

  MKR_ADDRESS: TypedContractMethod<[], [string], "view">;

  bytes32ToString: TypedContractMethod<[_bytes32: BytesLike], [string], "view">;

  getReservesData: TypedContractMethod<
    [provider: AddressLike],
    [
      [
        IUiPoolDataProviderV3.AggregatedReserveDataStructOutput[],
        IUiPoolDataProviderV3.BaseCurrencyInfoStructOutput
      ]
    ],
    "view"
  >;

  getReservesList: TypedContractMethod<
    [provider: AddressLike],
    [string[]],
    "view"
  >;

  getUserReservesData: TypedContractMethod<
    [provider: AddressLike, user: AddressLike],
    [[IUiPoolDataProviderV3.UserReserveDataStructOutput[], bigint]],
    "view"
  >;

  marketReferenceCurrencyPriceInUsdPriceId: TypedContractMethod<
    [],
    [string],
    "view"
  >;

  networkBaseTokenPriceInUsdPriceId: TypedContractMethod<[], [string], "view">;

  pyth: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ETH_CURRENCY_UNIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MKR_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bytes32ToString"
  ): TypedContractMethod<[_bytes32: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getReservesData"
  ): TypedContractMethod<
    [provider: AddressLike],
    [
      [
        IUiPoolDataProviderV3.AggregatedReserveDataStructOutput[],
        IUiPoolDataProviderV3.BaseCurrencyInfoStructOutput
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReservesList"
  ): TypedContractMethod<[provider: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserReservesData"
  ): TypedContractMethod<
    [provider: AddressLike, user: AddressLike],
    [[IUiPoolDataProviderV3.UserReserveDataStructOutput[], bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "marketReferenceCurrencyPriceInUsdPriceId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "networkBaseTokenPriceInUsdPriceId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pyth"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
